name: Auto merge
on: pull_request

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-merge autorelease PRs
        uses: KeisukeYamashita/create-comment@v1
        with:
          intervalSeconds: 1
          timeoutSeconds: 60
          labels: "autorelease: pending"
          comment: ${{ steps.merge.outputs.merged }}
